// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwdT9oTWUQfo5j8dvRKVWrg6dcsXji2Jg',
    appId: '1:584936668036:web:db1bcf5a58bbfce5d7bbd1',
    messagingSenderId: '584936668036',
    projectId: 'dwidaffa-db55f',
    authDomain: 'dwidaffa-db55f.firebaseapp.com',
    storageBucket: 'dwidaffa-db55f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeJ3GIEWV8xZ7Dscv6vAGAwe06vmb6FgE',
    appId: '1:584936668036:android:304c44460ffed3a2d7bbd1',
    messagingSenderId: '584936668036',
    projectId: 'dwidaffa-db55f',
    storageBucket: 'dwidaffa-db55f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-CGkynVLYh1boHzhcAok-apN4lkjHPgQ',
    appId: '1:584936668036:ios:0dd08e97dea76504d7bbd1',
    messagingSenderId: '584936668036',
    projectId: 'dwidaffa-db55f',
    storageBucket: 'dwidaffa-db55f.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-CGkynVLYh1boHzhcAok-apN4lkjHPgQ',
    appId: '1:584936668036:ios:0dd08e97dea76504d7bbd1',
    messagingSenderId: '584936668036',
    projectId: 'dwidaffa-db55f',
    storageBucket: 'dwidaffa-db55f.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
